apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
  namespace: argocd
spec:
  description: Project for monorepo apps
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/byteling/kubernetes-C60"
    - "https://kubernetes.github.io/dashboard/"
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: ""
      kind: Namespace
    # Next 2: Longhorn / metallb
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
