apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
  namespace: argocd
spec:
  description: Project for monorepo apps
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/byteling/C59y"
    - "https://kubernetes.github.io/dashboard/"
