apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  project: project
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx/" # Helm repo URL
    chart: ingress-nginx

  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
