apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://portainer.github.io/k8s/" # Helm repo URL
    chart: portainer
    targetRevision: 2.33.2
    helm:
      values: |
        service:
          type: LoadBalancer
        tls:
          force: true
        image:
          tag: lts
  destination:
    server: "https://kubernetes.default.svc"
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/imagePullSecrets
